#\DeclareLyXModule{Standard Theorems (Numbered by Section)}
#\DeclareCategory{Maths}
#DescriptionBegin
#Numbers theorems and the like by section (i.e., the counter is reset at
#each section start).
#DescriptionEnd
#Requires: theorems-std | theorems-ams
#Excludes: theorems-chap

# Author: Richard Kimberly Heck <rikiheck@lyx.org>

Format 109

Counter theorem
	GuiName Theorem
	Within section
	LaTeXName thm
	RefFormat thm "Theorem|Theorems \thesection.\arabic{theorem}"
	RefFormat cor "Corollary|Corollaries \thesection.\arabic{theorem}"
	RefFormat lem "Lemma|Lemmas \thesection.\arabic{theorem}"
	RefFormat prop "Proposition|Propositions \thesection.\arabic{theorem}"
	RefFormat conj "Conjecture|Conjectures \thesection.\arabic{theorem}"
	RefFormat def "Definition|Definitions \thesection.\arabic{theorem}"
	RefFormat exa "Example|Examples \thesection.\arabic{theorem}"
	RefFormat prob "Problem|Problems \thesection.\arabic{theorem}"
	RefFormat exer "Exercise|Exercises \thesection.\arabic{theorem}"
	RefFormat solu "Solution|Solutions \thesection.\arabic{theorem}"
	RefFormat rem "Remark|Remarks \thesection.\arabic{theorem}"
	RefFormat claim "Claim|Claims \thesection.\arabic{theorem}"
	RefFormat fact "Fact|Facts \thesection.\arabic{theorem}"
	RefFormat cri "Criterion|Criteria \thesection.\arabic{theorem}"
	RefFormat alg "Algorithm|Algorithms \thesection.\arabic{theorem}"
End

Style Theorem
	TheoremParentCounter  section
End
