# Theorem-like counters, separately for each type of theorem

Format 109
Counter theorem
	GuiName Theorem
	LaTeXName thm
	PrettyFormat "Theorem|Theorems \arabic{theorem}"
End
Counter corollary
	GuiName Corollary
	LaTeXName cor
	PrettyFormat "Corollary|Corollaries \arabic{theorem}"
End
Counter lemma
	GuiName Lemma
	LaTeXName lem
	PrettyFormat "Lemma|Lemmas \arabic{theorem}"
End
Counter proposition
	GuiName Proposition
	LaTeXName prop
	PrettyFormat "Proposition|Propositions \arabic{theorem}"
End
Counter conjecture
	GuiName Conjecture
	PrettyFormat "Conjecture|Conjectures \arabic{theorem}"
End
Counter fact
	GuiName Fact
	PrettyFormat "Fact|Facts \arabic{theorem}"
End
Counter definition
	GuiName Definition
	LaTeXName defn
	PrettyFormat "Definition|Definitions \arabic{theorem}"
End
Counter example
	GuiName Example
	PrettyFormat "Example|Examples \arabic{theorem}"
End
Counter problem
	GuiName Problem
	PrettyFormat "Problem|Problems \arabic{theorem}"
End
Counter exercise
	GuiName Exercise
	LaTeXName xca
	PrettyFormat "Exercise|Exercises \arabic{theorem}"
End
Counter solution
	GuiName Solution
	LaTeXName sol
	PrettyFormat "Solution|Solutions \arabic{theorem}"
End
Counter remark
	GuiName Remark
	LaTeXName rem
	PrettyFormat "Remark|Remarks \arabic{theorem}"
End
Counter claim
	GuiName Claim
	PrettyFormat "Claim|Claims \arabic{theorem}"
End
