#\DeclareLyXModule{Standard Theorems (Numbered by Chapter)}
#\DeclareCategory{Maths}
#DescriptionBegin
#Numbers theorems and the like by chapter (i.e., the counter is reset at
#each chapter start). Use this module only with document classes that provide a chapter
#environment.
#DescriptionEnd
#Requires: theorems-std | theorems-ams
#Excludes: theorems-sec

# Author: Richard Kimberly Heck <rikiheck@lyx.org>

Format 109

Counter theorem
	GuiName Theorem
	Within chapter
	LaTeXName thm
	RefFormat thm "Theorem|Theorems \thechapter.\arabic{theorem}"
	RefFormat cor "Corollary|Corollaries \thechapter.\arabic{theorem}"
	RefFormat lem "Lemma|Lemmas \thechapter.\arabic{theorem}"
	RefFormat prop "Proposition|Propositions \thechapter.\arabic{theorem}"
	RefFormat conj "Conjecture|Conjectures \thechapter.\arabic{theorem}"
	RefFormat def "Definition|Definitions \thechapter.\arabic{theorem}"
	RefFormat exa "Example|Examples \thechapter.\arabic{theorem}"
	RefFormat prob "Problem|Problems \thechapter.\arabic{theorem}"
	RefFormat exer "Exercise|Exercises \thechapter.\arabic{theorem}"
	RefFormat solu "Solution|Solutions \thechapter.\arabic{theorem}"
	RefFormat rem "Remark|Remarks \thechapter.\arabic{theorem}"
	RefFormat claim "Claim|Claims \thechapter.\arabic{theorem}"
	RefFormat fact "Fact|Facts \thechapter.\arabic{theorem}"
	RefFormat cri "Criterion|Criteria \thechapter.\arabic{theorem}"
	RefFormat alg "Algorithm|Algorithms \thechapter.\arabic{theorem}"
End

Style Theorem
	TheoremParentCounter  chapter
End
