# Theorem-like counters, extended, separately for each type of theorem

Format 109
Counter criterion
	GuiName Criterion
	PrettyFormat "Criterion|Criteria \arabic{theorem}"
End
Counter algorithm
	GuiName Algorithm
	LaTeXName lyxalgorithm
	PrettyFormat "Algorithm|Algorithms \arabic{theorem}"
End
Counter axiom
	GuiName Axiom
	LaTeXName ax
	PrettyFormat "Axiom|Axioms \arabic{theorem}"
End
Counter condition
	GuiName Condition
	PrettyFormat "Condition|Conditions \arabic{theorem}"
End
Counter note
	GuiName Note
	PrettyFormat "Note|Notes \arabic{theorem}"
End
Counter notation
	GuiName Notation
	PrettyFormat "Notation|Notations \arabic{theorem}"
End
Counter summary
	GuiName Summary
	PrettyFormat "Summary|Summaries \arabic{theorem}"
End
Counter conclusion
	GuiName Conclusion
	PrettyFormat "Conclusion|Conclusions \arabic{theorem}"
End
Counter assumption
	GuiName Assumption
	PrettyFormat "Assumption|Assumptions \arabic{theorem}"
End
Counter question
	GuiName Question
	PrettyFormat "Question|Questions \arabic{theorem}"
End
